#!/bin/sh
# Tomcat auto-start
#
# description: Auto-starts tomcat
# processname: tomcat
# pidfile: /var/run/tomcat.pid

case $1 in
start)
sh /usr/share/tomcat-9/bin/startup.sh
;;
stop)
sh /usr/share/tomcat-9/bin/shutdown.sh
;;
restart)
sh /usr/share/tomcat-9/bin/shutdown.sh
sh /usr/share/tomcat-9/bin/startup.sh
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac
exit 0
