apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: gcr.io/PROJECT_ID/IMAGE:latest
    newName: gcr.io/projec-id/rust-container
    newTag: latest