name: Docker CI/CD

on:
  push:
    branches:
      - main

env:
  API_IMAGE_NAME: github-api
  API_CONTAINER_NAME: github-api
  UI_IMAGE_NAME: github-ui
  UI_CONTAINER_NAME: github-ui
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  SSH_HOST: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SERVER_USERNAME }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud --quiet auth configure-docker

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./API.Dockerfile
          push: true
          tags: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:latest

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./UI.Dockerfile
          push: true
          tags: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.UI_IMAGE_NAME }}:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands to deploy API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            docker stop ${{ env.API_CONTAINER_NAME }} || true
            docker rm ${{ env.API_CONTAINER_NAME }} || true
            docker rmi gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:latest || true
            docker pull gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:latest
            docker run -d --name ${{ env.API_CONTAINER_NAME }} --restart always -p 5001:5001 gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:latest

      - name: Executing remote SSH commands to deploy UI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            docker stop ${{ env.UI_CONTAINER_NAME }} || true
            docker rm ${{ env.UI_CONTAINER_NAME }} || true
            docker rmi gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.UI_IMAGE_NAME }}:latest || true
            docker pull gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.UI_IMAGE_NAME }}:latest
            docker run -d --name ${{ env.UI_CONTAINER_NAME }} --restart always -p 5000:5000 gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.UI_IMAGE_NAME }}:latest