---
- name: Uninstall Jenkins and cleanup on multiple OS
  hosts: jenkins_servers
  become: true
  vars:
    java_package_debian: openjdk-17-jre
    java_package_rhel: java-17-openjdk

  tasks:

    - name: Check if Jenkins service exists on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      shell: |
        systemctl list-units --type service --all | grep -w jenkins
      register: jenkins_service_exists_debian
      failed_when: jenkins_service_exists_debian.rc > 1
      ignore_errors: yes

    - name: Stop Jenkins on Debian/Ubuntu if running
      when: ansible_os_family == "Debian" and jenkins_service_exists_debian.rc == 0
      systemd:
        name: jenkins
        state: stopped

    - name: Uninstall Jenkins and Java on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      apt:
        name:
          - jenkins
          - "{{ java_package_debian }}"
          - fontconfig
        state: absent
        purge: yes

    - name: Remove Jenkins repo from sources list on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Remove Jenkins keyring on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      ansible.builtin.file:
        path: /usr/share/keyrings/jenkins-keyring.asc
        state: absent

    - name: Remove Jenkins cache and log directories on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/cache/jenkins
        - /var/log/jenkins

    - name: Check if Jenkins data directory exists on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      stat:
        path: /var/lib/jenkins
      register: jenkins_data_dir

    - name: Remove Jenkins data directory on Debian/Ubuntu
      when: ansible_os_family == "Debian" and jenkins_data_dir.stat.exists
      ansible.builtin.file:
        path: /var/lib/jenkins
        state: absent
        recurse: yes
        force: yes

    - name: Check if Jenkins service exists on Red Hat/Fedora/Alma/Rocky
      when: ansible_os_family == "RedHat"
      shell: |
        systemctl list-units --type service --all | grep -w jenkins
      register: jenkins_service_exists_rhel
      failed_when: jenkins_service_exists_rhel.rc > 1
      ignore_errors: yes

    - name: Stop Jenkins on Red Hat/Fedora/Alma/Rocky if running
      when: ansible_os_family == "RedHat" and jenkins_service_exists_rhel.rc == 0
      systemd:
        name: jenkins
        state: stopped

    - name: Uninstall Jenkins and Java on Red Hat/Fedora/Alma/Rocky
      when: ansible_os_family == "RedHat"
      yum:
        name:
          - jenkins
          - "{{ java_package_rhel }}"
          - fontconfig
        state: absent

    - name: Remove Jenkins repo file on Red Hat/Fedora/Alma/Rocky
      when: ansible_os_family == "RedHat"
      ansible.builtin.file:
        path: /etc/yum.repos.d/jenkins.repo
        state: absent

    - name: Remove Jenkins GPG key on Red Hat/Fedora/Alma/Rocky
      when: ansible_os_family == "RedHat" and jenkins_gpg_key is defined and jenkins_gpg_key is not none
      ansible.builtin.rpm_key:
        state: absent
        key: gpg-pubkey
      register: jenkins_gpg_key

    - name: Remove Jenkins cache, log, and data directories on Red Hat/Fedora/Alma/Rocky
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: yes
      loop:
        - /var/cache/jenkins
        - /var/log/jenkins
        - /var/lib/jenkins