---
- name: Install Prometheus on Prometheus Servers
  hosts: prometheus
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: Download Prometheus archive
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

    - name: Extract Prometheus archive
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Prometheus binary
      ansible.builtin.command: mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus /usr/local/bin/prometheus
      notify: reload_prometheus

    - name: Ensure Prometheus binary is executable
      ansible.builtin.file:
        path: /usr/local/bin/prometheus
        mode: '0755'
        owner: prometheus
        group: prometheus

    - name: Move Promtool
      ansible.builtin.command: mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool /usr/local/bin/promtool

    - name: Move prometheus.yml
      ansible.builtin.copy:
        src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        remote_src: yes

    - name: Move console files
      ansible.builtin.command: mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/consoles /etc/prometheus/consoles

    - name: Move console libraries
      ansible.builtin.command: mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/console_libraries /etc/prometheus/console_libraries

    - name: Set permissions for Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
        recurse: yes
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Create Prometheus systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target
          
          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          Restart=on-failure
          RestartSec=5s
          ExecStart=/usr/local/bin/prometheus \
              --config.file /etc/prometheus/prometheus.yml \
              --storage.tsdb.path /var/lib/prometheus/ \
              --web.console.templates=/etc/prometheus/consoles \
              --web.console.libraries=/etc/prometheus/console_libraries \
              --web.listen-address=0.0.0.0:9090 \
              --web.enable-lifecycle \
              --log.level=info
          
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: yes
        state: started