name: .NET 7 Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build
      
    - name: Calculate new version
      id: calc_version
      run: echo "::set-output name=NEW_VERSION::$(echo $(($(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+$' | head -n 1 | tr -d v | awk -F. '{print $2 * 10 + $1 * 1000}') + 1)) | awk '{print int($1 / 1000)"."int($1 % 1000 / 10)}')"
      shell: bash

    - name: Create GitHub release
      uses: gh-actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      with:
        tag_name: v${{ steps.calc_version.outputs.NEW_VERSION }}
        release_name: Release ${{ steps.calc_version.outputs.NEW_VERSION }}
        body: |
          Changes in this release:
          - ...
