apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443