name: GitOps CI/CD

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: devopsjourneyuz
  CONTAINER_NAME: devops-journey-prod
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  MANIFEST_REPO_URL: ${{ secrets.MANIFEST_REPO_URL }}
  MANIFEST_PATH: ${{ secrets.MANIFEST_PATH }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: ['build_and_push']
    steps:
      - name: Update manifest repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.MANIFEST_REPO_URL }}
          path: manifests
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: main  
  
      - name: Update deployment.yaml in manifest repository
        run: |
          cd manifests
          echo "${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          new_image="${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
      
          sed -i "s|image: .*|image: $new_image|g" ${{ env.MANIFEST_PATH }}/deployment.yaml      
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add ${{ env.MANIFEST_PATH }}/deployment.yaml
          git diff --cached --exit-code || git commit -m "Update image tag to $new_image" && git push origin main