name: Docker CI/CD

on:
  push:
    branches:
      - main

env:
  CONTAINER_NAME: devops-journey
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  MANIFEST_REPO_URL: ${{ secrets.MANIFEST_REPO_URL }}
  MANIFEST_PATH: ${{ secrets.MANIFEST_PATH }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${GITHUB_TOKEN}" | docker login -u "${{ github.actor }}" --password-stdin "${{ env.REGISTRY }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
  
  update-manifest:
    runs-on: ubuntu-latest
    needs: ['build_and_push']
    steps:
      - name: Update manifest repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.MANIFEST_REPO_URL }}
          path: manifests
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: main  

      - name: Update deployment.yaml in manifest repository
        run: |
          cd manifests
          echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          new_image="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        
          sed -i "s|image: .*|image: $new_image|g" ${{ env.MANIFEST_PATH }}/deployment.yaml      
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add ${{ env.MANIFEST_PATH }}/deployment.yaml
          git diff --cached --exit-code || git commit -m "Update image tag to $new_image" && git push origin main