name: Build and Release APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV

      - name: Rename APK with build date
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-$CURRENT_DATE.apk

      - name: List files
        run: ls -l app/build/outputs/apk/release/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_DATE }}
          release_name: Release ${{ env.CURRENT_DATE }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release-${{ env.CURRENT_DATE }}.apk
          asset_name: app-release-${{ env.CURRENT_DATE }}.apk
          asset_content_type: application/vnd.android.package-archive