name: Android CI
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  cache-gradle:
    name: Cache Gradle dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
 
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
 
  lint:
    name: Perform lint check
    needs: [cache-gradle]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
 
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
 
      - name: Make Gradle executable
        run: chmod +x ./gradlew
 
      - name: Run lint
        run: ./gradlew lintDebug
 
      - name: Upload html test report
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html
 
  unit-test:
    name: Perform Unit Testing
    needs: [cache-gradle]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
 
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
 
      - name: Run tests
        run: ./gradlew test
 
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/
 
  instrumentation-test:
    name: Perform Instrumentation Testing
    needs: [cache-gradle]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
 
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
 
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
 
      - name: Upload Instrumentation Test report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected
 
  debug-apk:
    name: Generate Debug APK
    needs: [cache-gradle]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
 
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
 
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
 
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sample-app.apk
          path: app/build/outputs/apk/debug/app-debug.apk