name: Code Checkout

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: ismoilovdevml/devops-tools
            path: devops-tools